- name: variables
  hosts: localhost
  Vars: #variable declaration
    course: "Terraform"
    Trainer: "Sivakumar"
    Duration: "120hrs"
  tasks:
- name: print override information
  Vars: # Task level variables
     Course: "Devops"
  ansible.builtin.debug:
    msg: "Hi, We are learning Ansible {{course}} from Trainer {{Trainer}} sivakumar, Duration {{Duration}} is 120hrs."

- name: print information
  ansible.builtin.debug:
    msg: "Hi, We are learning Ansible {{course}} from Trainer {{Trainer}} sivakumar, Duration {{Duration}} is 120hrs."
